---
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_admin_username: admin
#jenkins_admin_password: admin
jenkins_updates_url: "https://updates.jenkins.io"
jenkins_plugins:
      - build-pipeline-plugin
      - Bitbucket
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugins_install_dependencies: true
jenkins_plugin_timeout: 120